CREATE TABLE PUBLIC.VENDOR
   (	VENDOR_ID NUMERIC(10,0), 
	VENDOR_NAME VARCHAR(100), 
	VENDOR_TYPE_ID NUMERIC(10,0) DEFAULT 1, 
	PREFERRED_IND VARCHAR(1) DEFAULT 'N', 
	CONTACT_NUMBER VARCHAR(100), 
	REPRESENTATIVE VARCHAR(100), 
	SORT_ORDER NUMERIC(5,0) DEFAULT 0, 
	LAST_MODIFIED_DATE DATE, 
	EXTERNAL_IDENTIFIER VARCHAR(100), 
	COMMENTS VARCHAR(4000)
   )

Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (3,'Colorado Department of Public Health and Environment',2,'N',null,null,0,to_date('09-06-21','RR-MM-DD'),null,null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (4,'Kansas Department of Health & Environment',2,'N',null,null,0,to_date('09-06-21','RR-MM-DD'),null,null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (5,'Louisiana DEQ',2,'N',null,null,0,to_date('14-11-10','RR-MM-DD'),null,null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (6,'New Mexico Environmental Department',2,'N',null,null,0,to_date('09-06-21','RR-MM-DD'),null,null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (7,'Texas Commission on Environmental Quality',2,'N',null,null,0,to_date('09-06-21','RR-MM-DD'),null,null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (8,'N/A',1,'N',null,null,0,to_date('09-06-21','RR-MM-DD'),null,null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (9,'Mountain States Hotshot, LLC',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-367',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (10,'Mountain Supply & Services',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-368',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (11,'Mountainstate Power Tong, LLC.',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-369',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (12,'Multi-Shot, LLC',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-370',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (13,'Muskingum Watershed Conservancy',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-371',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (14,'MWCD',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-372',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (15,'Myers Well Service Inc',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-373',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (16,'Nabors Completion & Production Services',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-374',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (17,'NALCO Champion',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-375',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (18,'National Lime & Stone Company',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-376',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (19,'National Oilwell Varco LP',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-377',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (20,'Native American Marketing LLC',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-378',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (21,'Natural Gas Services Group Inc',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-379',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (22,'New Prospect Company',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-380',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (23,'New Tech Global Ventures, LLC',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-381',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (24,'Newalta Environmental Services Inc.',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-382',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (25,'Newpark Drilling Fluids, Inc.',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-383',null);
Insert into PUBLIC.VENDOR (VENDOR_ID,VENDOR_NAME,VENDOR_TYPE_ID,PREFERRED_IND,CONTACT_NUMBER,REPRESENTATIVE,SORT_ORDER,LAST_MODIFIED_DATE,EXTERNAL_IDENTIFIER,COMMENTS) values (26,'Nicolozakes Trucking & Construction Inc.',4,'N',null,null,0,to_date('15-06-16','RR-MM-DD'),'GPE-384',null);

Select * FROM PUBLIC.VENDOR